//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub use super::chat_completions::Entity as ChatCompletions;
pub use super::meta_completions::Entity as MetaCompletions;
pub use super::text_completions::Entity as TextCompletions;
